version: '3' 
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
  api:
    depends_on:
      - postgres
    image: poojahk/psimpleblogapi
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /user/app/node_modules
      - ./:/usr/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
    ports:
      - "3000:3000"